### ISSUE TITLE
RealUrl 2.0 compatibility

### ISSUE THREAD

**Issue by fnagel** [Kephson/reint_mailtask_example#1]
Does this extension work with EXT:realurl 2.0.x? I implemented something similar in one of my extensions but it stopped working when using new version of RealUrl.

Any feedback using this extension with the new version of RealUrl?

**Comment by Kephson** [comment]
Hi, thanks for reporting. ich will check this issue.
One solution is to set the rootpage id directly in ViewHelpers and in templates.

**Comment by Kephson** [comment]
I added an issue in realurl repo, because I don't know at the moment how to fix this:
https://github.com/dmitryd/typo3-realurl/issues/105

**Comment by fnagel** [comment]
Seems this commit should help to solve our issue: https://github.com/dmitryd/typo3-realurl/commit/a719c7f80d1989196af4530408b63d44feffd875

**Comment by Kephson** [comment]
Thanks, with version 2.0.11 of realurl the problem is fixed.

**Comment by fnagel** [comment]
Confirmed for my extension, too.
